name: 'SystemVerilog Linter'
author: 'dalance'
description: 'SystemVerilog source code check by svlint'
inputs:
  files:
    description: 'filenames of SystemVerilog source code'
    required: false
  filelists:
    description: 'filenames of filelist'
    required: false
runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/dalance/svlint-action/svlint-action:latest'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.filelists }}
branding:
  icon: 'check-circle'
  color: 'orange'
