name: 'SystemVerilog Linter'
author: 'dalance'
description: 'SystemVerilog source code check by svlint'
inputs:
  files:
    description: 'Paths to SystemVerilog source files.'
    required: false
  filelists:
    description: 'Paths to filelist files.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.filelists }}
branding:
  icon: 'check-circle'
  color: 'orange'
