name: Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login GitHub Registry
      run: docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/svlint-action:latest .

    - name: Push image to GitHub Registry
      run: docker push docker.pkg.github.com/${{ github.repository }}/svlint-action:latest
