on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
    - name: Test
      uses: dalance/svlint-action@v1
      with:
        files: 'a.sv b.sv'
        filelists: 'a.f b.f'
