name: Regression

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: dalance/svlint-action@master
      with:
        files: 'a.sv b.sv'
        filelists: 'a.f b.f'
